# This docker-compose helps to setup containers for integration tests.
#
# USAGE:
# In the root of the project, start containers using:
#
#   docker-compose --file ./e2e/docker-compose.yml up -d
#
# Then run tests with additional environment variables:
#
#   TEST_AMQP_URL=amqp://localhost TEST_MANAGEMENT_URL=http://guest:guest@localhost:15672 TEST_PHPFPM_ADDR=localhost:9000 go test ./...
#
version: "2"
services:
  phpfpm:
    image: php:7-fpm-alpine
    container_name: phpfpm
    ports:
      - 9000:9000
    volumes:
      - ../bridge:/amqp-cgi-bridge
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
